import classNames from "classnames";
import type { Metadata } from "next";
import { onest } from "./fonts/onest";
import "./styles/globals.css";
import "@radix-ui/themes/styles.css";

import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(styles.component, onest.className)}>
        {children}
      </body>
    </html>
  );
}
